### ISSUE TITLE
Trouble running on Macbook Air

### ISSUE THREAD

**Issue by jkanner** [camurria/GW_Data_Plotter#2]
Hi, 

This app looks great!

I am having trouble running the app on my Macbook Air using an M2 chip.  I get this error message.  Can you give me advice on how to run the app?  Thank you

<img width="257" alt="Screenshot 2024-10-10 at 9 29 34 AM" src="https://github.com/user-attachments/assets/d94a2391-3c09-4df0-8528-0f6d929e28ca">

**Comment by camurria** [comment]
See this note from zenodo: 

- **Note for Mac Users**: Since this app doesn't come from the Apple App Store and is not directly notarized by Apple, when you try to open it by double-clicking on the icon the system will display a warning message that doesn't allow you to open it. To avoid this problem you can change the Privacy & Security settings as explained in [this link](https://support.apple.com/en-us/102445). Alternatively, you can also press CTRL while clicking on the icon. This will open a menu, from which you have to select "Open". At this point, you will see the same warning window you saw before with the option "Open" in addition.
