### ISSUE TITLE
404 error with skymap for GW190512

### ISSUE THREAD

**Issue by camurria** [camurria/GW_Data_Plotter#7]
This issue concerns the third tab. 

The download skymap button has some logic that is used to dwonload the skymap from gracedb when it is available otherwise it uses the one from gwcat. This logic seems not to work for the event GW190512 for which the downloading gives the error: `HTTP Error 404: Not Found`. 
I see two possible causes of error to check:

1. the link to gracedb is not correct, i.e., the skymap file has a different name than the one expected
2. the logic to chose if downloading from gracedb or from gwcat is not working.

**Comment by piosif** [comment]
In the GWOSC catalog there is no event named **GW190512**.
There is an event named **GW190512_180714**.
When requesting event **GW190512** from the 3rd tab, the request points to the event **GW190512_180714**.

The 404 error occurs because when formulating the URL link to download the skymap, the expected filename uses the GW event name **as typed by the user** (i.e., GW190512).

Since there is no skymap file named "GW190512_PublicationSamples.png" the program cannot fetch it and thus the error occurs.
However, a skymap file named "GW190512_180714_PublicationSamples.png" **does exist**.

The related section in the code has been amended (see [commit 1ee91d5 of certificates_check branch](https://github.com/camurria/GW_Data_Plotter/commit/1ee91d50e9c07d61f5cf33affa439d3ec7e4e388) and now this is solved.

This change is pending to be merged in the next version of the app.

**Comment by piosif** [comment]
Fixed in new version of app, now published on Zenodo, see: https://zenodo.org/records/14530424
